In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("task_data.csv")

In [3]:
df

ID Delivery_person_ID  Delivery_person_Age   
0      0xcdcd      DEHRES17DEL01                 36.0  \
1      0xd987      KOCRES16DEL01                 21.0   
2      0x2784     PUNERES13DEL03                 23.0   
3      0xc8b6     LUDHRES15DEL02                 34.0   
4      0xdb64      KNPRES14DEL02                 24.0   
...       ...                ...                  ...   
45579  0x7c09      JAPRES04DEL01                 30.0   
45580  0xd641      AGRRES16DEL01                 21.0   
45581  0x4f8d     CHENRES08DEL03                 30.0   
45582  0x5eee    COIMBRES11DEL01                 20.0   
45583  0x5fb2   RANCHIRES09DEL02                 23.0   

       Delivery_person_Ratings  Restaurant_latitude  Restaurant_longitude   
0                          4.2            30.327968             78.046106  \
1                          4.7            10.003064             76.307589   
2                          4.7            18.562450             73.916619   
3                          4.3            30.899584             75.809346   
4                          4.7            26.463504             80.372929   
...                        ...                  ...                   ...   
45579                      4.8            26.902328             75.794257   
45580                      4.6             0.000000              0.000000   
45581                      4.9            13.022394             80.242439   
45582                      4.7            11.001753             76.986241   
45583                      4.9            23.351058             85.325731   

       Delivery_location_latitude  Delivery_location_longitude  Order_Date   
0                       30.397968                    78.116106  12-02-2022  \
1                       10.043064                    76.347589  13-02-2022   
2                       18.652450                    74.006619  04-03-2022   
3                       30.919584                    75.829346  13-02-2022   
4                       26.593504                    80.502929  14-02-2022   
...                           ...                          ...         ...   
45579                   26.912328                    75.804257  24-03-2022   
45580                    0.070000                     0.070000  16-02-2022   
45581                   13.052394                    80.272439  11-03-2022   
45582                   11.041753                    77.026241  07-03-2022   
45583                   23.431058                    85.405731  02-03-2022   

      Time_Orderd Time_Order_picked Weather_conditions Road_traffic_density   
0           21:55             22:10                Fog                  Jam  \
1           14:55             15:05             Stormy                 High   
2           17:30             17:40         Sandstorms               Medium   
3           09:20             09:30         Sandstorms                  Low   
4           19:50             20:05                Fog                  Jam   
...           ...               ...                ...                  ...   
45579       11:35             11:45              Windy                 High   
45580       19:55             20:10              Windy                  Jam   
45581       23:50          24:05:00             Cloudy                  Low   
45582       13:35             13:40             Cloudy                 High   
45583       17:10             17:15                Fog               Medium   

       Vehicle_condition Type_of_order Type_of_vehicle  multiple_deliveries   
0                      2         Snack      motorcycle                  3.0  \
1                      1          Meal      motorcycle                  1.0   
2                      1        Drinks         scooter                  1.0   
3                      0        Buffet      motorcycle                  0.0   
4                      1         Snack         scooter                  1.0   
...                  ...           ...   

In [4]:
# we have a zomato data .we need need to predict time 

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45584 entries, 0 to 45583
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   ID                           45584 non-null  object 
 1   Delivery_person_ID           45584 non-null  object 
 2   Delivery_person_Age          43730 non-null  float64
 3   Delivery_person_Ratings      43676 non-null  float64
 4   Restaurant_latitude          45584 non-null  float64
 5   Restaurant_longitude         45584 non-null  float64
 6   Delivery_location_latitude   45584 non-null  float64
 7   Delivery_location_longitude  45584 non-null  float64
 8   Order_Date                   45584 non-null  object 
 9   Time_Orderd                  43853 non-null  object 
 10  Time_Order_picked            45584 non-null  object 
 11  Weather_conditions           44968 non-null  object 
 12  Road_traffic_density         44983 non-null  object 
 13  Vehicle_conditio

In [6]:
# i drop "ID" column bcoz it is not usebal
df.drop(labels=["ID"],axis=1,inplace=True)

In [7]:
df.head()

Delivery_person_ID  Delivery_person_Age  Delivery_person_Ratings   
0      DEHRES17DEL01                 36.0                      4.2  \
1      KOCRES16DEL01                 21.0                      4.7   
2     PUNERES13DEL03                 23.0                      4.7   
3     LUDHRES15DEL02                 34.0                      4.3   
4      KNPRES14DEL02                 24.0                      4.7   

   Restaurant_latitude  Restaurant_longitude  Delivery_location_latitude   
0            30.327968             78.046106                   30.397968  \
1            10.003064             76.307589                   10.043064   
2            18.562450             73.916619                   18.652450   
3            30.899584             75.809346                   30.919584   
4            26.463504             80.372929                   26.593504   

   Delivery_location_longitude  Order_Date Time_Orderd Time_Order_picked   
0                    78.116106  12-02-2022       21:55             22:10  \
1                    76.347589  13-02-2022       14:55             15:05   
2                    74.006619  04-03-2022       17:30             17:40   
3                    75.829346  13-02-2022       09:20             09:30   
4                    80.502929  14-02-2022       19:50             20:05   

  Weather_conditions Road_traffic_density  Vehicle_condition Type_of_order   
0                Fog                  Jam                  2         Snack  \
1             Stormy                 High                  1          Meal   
2         Sandstorms               Medium                  1        Drinks   
3         Sandstorms                  Low                  0        Buffet   
4                Fog                  Jam                  1         Snack   

  Type_of_vehicle  multiple_deliveries Festival           City   
0      motorcycle                  3.0       No  Metropolitian  \
1      motorcycle                  1.0       No  Metropolitian   
2         scooter                  1.0       No  Metropolitian   
3      motorcycle                  0.0       No  Metropolitian   
4         scooter                  1.0       No  Metropolitian   

   Time_taken (min)  
0                46  
1                23  
2                21  
3                20  
4                41

In [8]:
df.describe()

Delivery_person_Age  Delivery_person_Ratings  Restaurant_latitude   
count         43730.000000             43676.000000         45584.000000  \
mean             29.566911                 4.633774            17.017948   
std               5.815064                 0.334744             8.185674   
min              15.000000                 1.000000           -30.905562   
25%              25.000000                 4.500000            12.933284   
50%              30.000000                 4.700000            18.551440   
75%              35.000000                 4.900000            22.728163   
max              50.000000                 6.000000            30.914057   

       Restaurant_longitude  Delivery_location_latitude   
count          45584.000000                45584.000000  \
mean              70.229684                   17.465480   
std               22.885575                    7.335562   
min              -88.366217                    0.010000   
25%               73.170000                   12.988453   
50%               75.897963                   18.633934   
75%               78.044095                   22.785049   
max               88.433452                   31.054057   

       Delivery_location_longitude  Vehicle_condition  multiple_deliveries   
count                 45584.000000       45584.000000         44591.000000  \
mean                     70.844161           1.023385             0.744635   
std                      21.120578           0.839055             0.572510   
min                       0.010000           0.000000             0.000000   
25%                      73.280000           0.000000             0.000000   
50%                      76.002574           1.000000             1.000000   
75%                      78.107044           2.000000             1.000000   
max                      88.563452           3.000000             3.000000   

       Time_taken (min)  
count      45584.000000  
mean          26.293963  
std            9.384298  
min           10.000000  
25%           19.000000  
50%           26.000000  
75%           32.000000  
max           54.000000

## In data  Analysis what all things we do
1.missing values
2.Explore about the numerical value
3.explore about categorical variable
4.finding relationship between feature

In [9]:

df.drop("Delivery_person_ID",axis=1,inplace=True)
df.sample(5)

Delivery_person_Age  Delivery_person_Ratings  Restaurant_latitude   
22335                 35.0                      4.8            19.131141  \
22159                 38.0                      4.6            19.223840   
19904                 31.0                      4.8            12.311072   
36398                 28.0                      4.7            22.751234   
10516                 31.0                      4.6            21.170798   

       Restaurant_longitude  Delivery_location_latitude   
22335             72.813074                   19.261140  \
22159             72.841347                   19.293840   
19904             76.654878                   12.331072   
36398             75.889490                   22.881234   
10516             72.790489                   21.230798   

       Delivery_location_longitude  Order_Date Time_Orderd Time_Order_picked   
22335                    72.943074  04-04-2022       20:50             20:55  \
22159                    72.911347  29-03-2022       21:30             21:35   
19904                    76.674878  30-03-2022       11:50               0.5   
36398                    76.019490  02-04-2022       19:20             19:35   
10516                    72.850489  05-04-2022       0.875             21:15   

      Weather_conditions Road_traffic_density  Vehicle_condition   
22335             Cloudy                  Jam                  0  \
22159              Sunny                  Jam                  0   
19904         Sandstorms                 High                  2   
36398             Cloudy                  Jam                  0   
10516              Sunny                  Jam                  1   

      Type_of_order Type_of_vehicle  multiple_deliveries Festival   
22335          Meal      motorcycle                  1.0      Yes  \
22159         Snack      motorcycle                  2.0       No   
19904         Snack      motorcycle                  0.0       No   
36398          Meal      motorcycle                  1.0      Yes   
10516        Buffet      motorcycle                  1.0       No   

                City  Time_taken (min)  
22335  Metropolitian                50  
22159  Metropolitian                40  
19904  Metropolitian                32  
36398  Metropolitian                49  
10516  Metropolitian                24

In [10]:
df["order_day"]=pd.to_datetime(df["Order_Date"],dayfirst=True).dt.day
df["order_month"]=pd.to_datetime(df["Order_Date"],dayfirst=True).dt.month
#i am not create year columns because they not effect more our data .its only 2022

In [11]:
df["order_day"]

0        12
1        13
2         4
3        13
4        14
         ..
45579    24
45580    16
45581    11
45582     7
45583     2
Name: order_day, Length: 45584, dtype: int32

In [12]:
df["order_month"]

0        2
1        2
2        3
3        2
4        2
        ..
45579    3
45580    2
45581    3
45582    3
45583    3
Name: order_month, Length: 45584, dtype: int32

In [13]:
df["Time_Orderd"].unique()
#when we look in the data than got not same manner values 

array(['21:55', '14:55', '17:30', '09:20', '19:50', '20:25', '20:30',
       '20:40', '21:15', '20:20', '22:30', '08:15', '19:30', '12:25',
       '18:35', '20:35', '23:20', '21:20', '23:35', '22:35', '23:25',
       '13:35', '21:35', '18:55', '14:15', '0.458333333', '09:45',
       '08:40', '0.958333333', '17:25', nan, '19:45', '19:10', '10:55',
       '21:40', '0.791666667', '16:45', '11:30', '15:10', '22:45',
       '22:10', '20:45', '22:50', '17:55', '09:25', '20:15', '22:25',
       '22:40', '23:50', '15:25', '10:20', '20:55', '10:40', '15:55',
       '20:10', '12:10', '15:30', '10:35', '21:10', '20:50', '12:35',
       '0.875', '23:40', '18:15', '18:20', '11:45', '12:45', '23:30',
       '10:50', '21:25', '10:10', '17:50', '22:20', '12:40', '23:55',
       '10:25', '08:45', '23:45', '19:55', '22:15', '23:10', '09:15',
       '18:25', '18:45', '16:50', '1', '14:20', '10:15', '08:50', '0.375',
       '17:45', '16:35', '08:30', '21:45', '19:40', '14:50', '18:10',
       '12:20', '12

In [14]:
df["Time_Orderd"]=df["Time_Orderd"].str.replace(".",":")

In [15]:
df["Time_Orderd"].unique()

array(['21:55', '14:55', '17:30', '09:20', '19:50', '20:25', '20:30',
       '20:40', '21:15', '20:20', '22:30', '08:15', '19:30', '12:25',
       '18:35', '20:35', '23:20', '21:20', '23:35', '22:35', '23:25',
       '13:35', '21:35', '18:55', '14:15', '0:458333333', '09:45',
       '08:40', '0:958333333', '17:25', nan, '19:45', '19:10', '10:55',
       '21:40', '0:791666667', '16:45', '11:30', '15:10', '22:45',
       '22:10', '20:45', '22:50', '17:55', '09:25', '20:15', '22:25',
       '22:40', '23:50', '15:25', '10:20', '20:55', '10:40', '15:55',
       '20:10', '12:10', '15:30', '10:35', '21:10', '20:50', '12:35',
       '0:875', '23:40', '18:15', '18:20', '11:45', '12:45', '23:30',
       '10:50', '21:25', '10:10', '17:50', '22:20', '12:40', '23:55',
       '10:25', '08:45', '23:45', '19:55', '22:15', '23:10', '09:15',
       '18:25', '18:45', '16:50', '1', '14:20', '10:15', '08:50', '0:375',
       '17:45', '16:35', '08:30', '21:45', '19:40', '14:50', '18:10',
       '12:20', '12

In [16]:
#After replace we need to splite the data hours ans mins
df["order_hours"]=df["Time_Orderd"].str.split(":").str[0]
df["order_min"]=df["Time_Orderd"].str.split(":").str[1]


In [17]:
df["order_hours"]=df["order_hours"].astype(float)
df["order_min"]=df["order_min"].astype(float)

In [18]:
df["order_hours"].unique()

array([21., 14., 17.,  9., 19., 20., 22.,  8., 12., 18., 23., 13.,  0.,
       nan, 10., 16., 11., 15.,  1.])

In [19]:
df["order_min"].unique()

array([5.50000000e+01, 3.00000000e+01, 2.00000000e+01, 5.00000000e+01,
       2.50000000e+01, 4.00000000e+01, 1.50000000e+01, 3.50000000e+01,
       4.58333333e+08, 4.50000000e+01, 9.58333333e+08,            nan,
       1.00000000e+01, 7.91666667e+08, 8.75000000e+02, 3.75000000e+02,
       6.25000000e+02, 8.33333333e+08, 6.66666667e+08, 7.50000000e+01,
       4.16666667e+08, 9.16666667e+08, 5.00000000e+00, 7.08333333e+08,
       5.41666667e+08, 5.83333333e+08])

In [20]:
#when look into the order_min than we got its not good as we want than we use some auto mation
for i in df["order_min"]:
    if i>60:
        p=i-60
        df["order_min"]=df["order_min"].replace(i,i-p)

#why 60?
#bcoz 1 hour have 60 min

In [21]:
df["order_min"].unique()

array([55., 30., 20., 50., 25., 40., 15., 35., 60., 45., nan, 10.,  5.])

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45584 entries, 0 to 45583
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Delivery_person_Age          43730 non-null  float64
 1   Delivery_person_Ratings      43676 non-null  float64
 2   Restaurant_latitude          45584 non-null  float64
 3   Restaurant_longitude         45584 non-null  float64
 4   Delivery_location_latitude   45584 non-null  float64
 5   Delivery_location_longitude  45584 non-null  float64
 6   Order_Date                   45584 non-null  object 
 7   Time_Orderd                  43853 non-null  object 
 8   Time_Order_picked            45584 non-null  object 
 9   Weather_conditions           44968 non-null  object 
 10  Road_traffic_density         44983 non-null  object 
 11  Vehicle_condition            45584 non-null  int64  
 12  Type_of_order                45584 non-null  object 
 13  Type_of_vehicle 

In [23]:
df["Time_Order_picked"].unique()

array(['22:10', '15:05', '17:40', '09:30', '20:05', '20:35', '15:10',
       '20:40', '20:50', '21:30', '20:25', '22:45', '08:30', '19:45',
       '12:30', '18:50', '23:30', '21:35', '23:45', '22:50', '22:40',
       '23:35', '13:40', '21:45', '19:10', '14:25', '11:10', '09:55',
       '08:55', '23:10', '17:30', '18:35', '19:50', '19:25',
       '0.458333333', '19:15', '16:55', '11:40', '15:15', '22:55',
       '22:25', '20:55', '23:05', '0.75', '0.958333333', '09:40', '20:20',
       '22:35', '0.916666667', '23:55', '15:40', '10:30', '0.875',
       '10:50', '16:05', '20:15', '12:15', '15:45', '22:15', '10:45',
       '15:30', '24:05:00', '21:25', '12:45', '21:15', '18:20', '18:25',
       '11:50', '12:50', '10:55', '21:40', '10:20', '17:55', '23:50',
       '12:55', '24:10:00', '10:40', '0.375', '20:45', '0.833333333',
       '23:15', '22:20', '21:05', '0.708333333', '24:15:00', '21:20',
       '14:35', '10:25', '09:05', '16:50', '08:40', '23:40', '21:50',
       '19:55', '0.625', '1

In [24]:
df["Time_Order_picked"]=df["Time_Order_picked"].str.replace(".",":")

In [25]:
df["picked_hours"]=df["Time_Order_picked"].str.split(":").str[0]
df["picked_min"]=df["Time_Order_picked"].str.split(":").str[1]
df["picked_hours"]=df["picked_hours"].astype(float)
df["picked_min"]=df["picked_min"].astype(float)

In [26]:
df["picked_hours"].unique()

array([22., 15., 17.,  9., 20., 21.,  8., 19., 12., 18., 23., 13., 14.,
       11.,  0., 16., 10., 24.,  1.])

In [27]:
df["picked_min"].unique()

array([1.00000000e+01, 5.00000000e+00, 4.00000000e+01, 3.00000000e+01,
       3.50000000e+01, 5.00000000e+01, 2.50000000e+01, 4.50000000e+01,
       5.50000000e+01, 4.58333333e+08, 1.50000000e+01, 7.50000000e+01,
       9.58333333e+08, 2.00000000e+01, 9.16666667e+08, 8.75000000e+02,
       3.75000000e+02, 8.33333333e+08, 7.08333333e+08, 6.25000000e+02,
                  nan, 7.91666667e+08, 5.41666667e+08, 4.16666667e+08,
       5.83333333e+08, 6.66666667e+08])

In [28]:
#when look into the order_min than we got its not good as we want than we use some auto mation
for i in df["picked_min"]:
    if i>60:
        p=i-60
        df["picked_min"]=df["picked_min"].replace(i,i-p)

#why 60?
#bcoz 1 hour have 60 min

In [29]:
df["picked_min"].unique()

array([10.,  5., 40., 30., 35., 50., 25., 45., 55., 60., 15., 20., nan])

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45584 entries, 0 to 45583
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Delivery_person_Age          43730 non-null  float64
 1   Delivery_person_Ratings      43676 non-null  float64
 2   Restaurant_latitude          45584 non-null  float64
 3   Restaurant_longitude         45584 non-null  float64
 4   Delivery_location_latitude   45584 non-null  float64
 5   Delivery_location_longitude  45584 non-null  float64
 6   Order_Date                   45584 non-null  object 
 7   Time_Orderd                  43853 non-null  object 
 8   Time_Order_picked            45584 non-null  object 
 9   Weather_conditions           44968 non-null  object 
 10  Road_traffic_density         44983 non-null  object 
 11  Vehicle_condition            45584 non-null  int64  
 12  Type_of_order                45584 non-null  object 
 13  Type_of_vehicle 

In [31]:
df.drop(labels=["Order_Date","Time_Orderd","Time_Order_picked"],axis=1,inplace=True)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45584 entries, 0 to 45583
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Delivery_person_Age          43730 non-null  float64
 1   Delivery_person_Ratings      43676 non-null  float64
 2   Restaurant_latitude          45584 non-null  float64
 3   Restaurant_longitude         45584 non-null  float64
 4   Delivery_location_latitude   45584 non-null  float64
 5   Delivery_location_longitude  45584 non-null  float64
 6   Weather_conditions           44968 non-null  object 
 7   Road_traffic_density         44983 non-null  object 
 8   Vehicle_condition            45584 non-null  int64  
 9   Type_of_order                45584 non-null  object 
 10  Type_of_vehicle              45584 non-null  object 
 11  multiple_deliveries          44591 non-null  float64
 12  Festival                     45356 non-null  object 
 13  City            

### Some Manual work

In [33]:
df.isnull().sum()

Delivery_person_Age            1854
Delivery_person_Ratings        1908
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Weather_conditions              616
Road_traffic_density            601
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             993
Festival                        228
City                           1200
Time_taken (min)                  0
order_day                         0
order_month                       0
order_hours                    1731
order_min                      2161
picked_hours                      0
picked_min                      440
dtype: int64

In [34]:
import numpy as np
print(np.mean(df["Delivery_person_Age"]))
print(np.mean(df["Delivery_person_Ratings"]))

29.566910587697233
4.6337736972250205


In [35]:
df["Delivery_person_Ratings"].fillna(4.6,inplace=True)
df["Delivery_person_Ratings"]=df["Delivery_person_Ratings"].astype(float)

In [36]:
df["Delivery_person_Age"].fillna(29,inplace=True)
df["Delivery_person_Age"]=df["Delivery_person_Age"].astype(float)

In [37]:
df["Weather_conditions"].unique()

array(['Fog', 'Stormy', 'Sandstorms', 'Windy', 'Cloudy', 'Sunny', nan],
      dtype=object)

In [38]:
df["Weather_conditions"].value_counts()

Weather_conditions
Fog           7653
Stormy        7584
Cloudy        7533
Sandstorms    7494
Windy         7422
Sunny         7282
Name: count, dtype: int64

In [39]:
df["Weather_conditions"].fillna("fog",inplace=True)

In [40]:
df["Weather_conditions"].unique()

array(['Fog', 'Stormy', 'Sandstorms', 'Windy', 'Cloudy', 'Sunny', 'fog'],
      dtype=object)

In [41]:
df["Road_traffic_density"].unique()
df["Road_traffic_density"].value_counts()

Road_traffic_density
Low       15476
Jam       14139
Medium    10945
High       4423
Name: count, dtype: int64

In [42]:
df["Road_traffic_density"].fillna("Low",inplace=True)

In [43]:
df["multiple_deliveries"].unique()

array([ 3.,  1.,  0., nan,  2.])

In [44]:
df["multiple_deliveries"].value_counts()

multiple_deliveries
1.0    28151
0.0    14094
2.0     1985
3.0      361
Name: count, dtype: int64

In [45]:
#this is also a categorical varibale tharefore i using most frequent value
df["multiple_deliveries"].fillna("1.0",inplace=True)

In [46]:
df["Festival"].unique()

array(['No', 'Yes', nan], dtype=object)

In [47]:
df["Festival"].value_counts()

Festival
No     44460
Yes      896
Name: count, dtype: int64

In [48]:
df["Festival"].fillna("No",inplace=True)

In [49]:
df["City"].unique()

array(['Metropolitian', 'Urban', 'Semi-Urban', nan], dtype=object)

In [50]:
df["City"].value_counts()

City
Metropolitian    34087
Urban            10133
Semi-Urban         164
Name: count, dtype: int64

In [51]:
df["City"].fillna("Metropolitian",inplace=True)

In [52]:
df["order_hours"].median()
#in real life we also say that mosly we order something in evening

18.0

In [53]:
df["order_hours"].fillna("18.0",inplace=True)

In [54]:
df["order_min"].value_counts()

order_min
35.0    4118
40.0    4027
45.0    3994
55.0    3993
20.0    3993
25.0    3975
10.0    3968
50.0    3966
30.0    3884
15.0    3867
60.0    3449
5.0      189
Name: count, dtype: int64

In [55]:
df["order_min"].mean()

34.640167653087076

In [56]:
df["order_min"].fillna(35,inplace=True)

In [57]:
df["picked_min"].value_counts()

picked_min
5.0     4374
30.0    4227
50.0    4196
45.0    4151
40.0    4123
25.0    4111
55.0    4110
35.0    4072
60.0    3499
10.0    2830
15.0    2811
20.0    2640
Name: count, dtype: int64

In [58]:
df["picked_min"].fillna(5.0,inplace=True)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45584 entries, 0 to 45583
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Delivery_person_Age          45584 non-null  float64
 1   Delivery_person_Ratings      45584 non-null  float64
 2   Restaurant_latitude          45584 non-null  float64
 3   Restaurant_longitude         45584 non-null  float64
 4   Delivery_location_latitude   45584 non-null  float64
 5   Delivery_location_longitude  45584 non-null  float64
 6   Weather_conditions           45584 non-null  object 
 7   Road_traffic_density         45584 non-null  object 
 8   Vehicle_condition            45584 non-null  int64  
 9   Type_of_order                45584 non-null  object 
 10  Type_of_vehicle              45584 non-null  object 
 11  multiple_deliveries          45584 non-null  object 
 12  Festival                     45584 non-null  object 
 13  City            

In [60]:
df.isnull().sum()
#there is null value

Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Weather_conditions             0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken (min)               0
order_day                      0
order_month                    0
order_hours                    0
order_min                      0
picked_hours                   0
picked_min                     0
dtype: int64

In [61]:
df

Delivery_person_Age  Delivery_person_Ratings  Restaurant_latitude   
0                     36.0                      4.2            30.327968  \
1                     21.0                      4.7            10.003064   
2                     23.0                      4.7            18.562450   
3                     34.0                      4.3            30.899584   
4                     24.0                      4.7            26.463504   
...                    ...                      ...                  ...   
45579                 30.0                      4.8            26.902328   
45580                 21.0                      4.6             0.000000   
45581                 30.0                      4.9            13.022394   
45582                 20.0                      4.7            11.001753   
45583                 23.0                      4.9            23.351058   

       Restaurant_longitude  Delivery_location_latitude   
0                 78.046106                   30.397968  \
1                 76.307589                   10.043064   
2                 73.916619                   18.652450   
3                 75.809346                   30.919584   
4                 80.372929                   26.593504   
...                     ...                         ...   
45579             75.794257                   26.912328   
45580              0.000000                    0.070000   
45581             80.242439                   13.052394   
45582             76.986241                   11.041753   
45583             85.325731                   23.431058   

       Delivery_location_longitude Weather_conditions Road_traffic_density   
0                        78.116106                Fog                  Jam  \
1                        76.347589             Stormy                 High   
2                        74.006619         Sandstorms               Medium   
3                        75.829346         Sandstorms                  Low   
4                        80.502929                Fog                  Jam   
...                            ...                ...                  ...   
45579                    75.804257              Windy                 High   
45580                     0.070000              Windy                  Jam   
45581                    80.272439             Cloudy                  Low   
45582                    77.026241             Cloudy                 High   
45583                    85.405731                Fog               Medium   

       Vehicle_condition Type_of_order  ... multiple_deliveries Festival   
0                      2         Snack  ...                 3.0       No  \
1                      1          Meal  ...                 1.0       No   
2                      1        Drinks  ...                 1.0       No   
3                      0        Buffet  ...                 0.0       No   
4                      1         Snack  ...                 1.0       No   
...                  ...           ...  ...                 ...      ...   
45579                  1          Meal  ...                 0.0       No   
45580                  0        Buffet  ...                 1.0       No   
45581                  1        Drinks  ...                 0.0       No   
45582                  0         Snack  ...                 1.0       No   
45583                  2         Snack  ...                 1.0       No   

                City Time_taken (min)  order_day  order_month  order_hours   
0      Metropolitian               46         12            2         21.0  \
1      Metropolitian               23         13            2         14.0   
2      Metropolitian               21          4            3         17.0   
3      Metropolitian               20         13            2          9.0   
4      Metropolitian               41         14            2         19.0   
...              ...              ...        ...          ...      

In [62]:
import seaborn as sns
